model:
  image_channels: 3
  lam_model_dim: 768
  lam_latent_dim: 128
  lam_num_latents: 16
  lam_patch_size: 14
  lam_enc_blocks: 12
  lam_dec_blocks: 12
  lam_num_heads: 12
  lam_pose_dim: 7
  lam_num_pose_tokens: 4

  vq_beta: 0.25
  log_interval: 5000
  log_path: ./logs
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-4
      weight_decay: 1e-2

  task_name: task_centric_lpm_stage2
  make_data_pair: false
  stage: stage-2
  stage_one_ckpt: ./logs/task_centric_lpm_stage1/last.ckpt

data:
  data_root: stage1_data/parsed_taco_data
  batch_size: 16
  resolution: 224
  num_workers: 4
  val_split: 0.1
  seed: 42

trainer:
  max_epochs: 20
  accelerator: gpu
  num_nodes: 1
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 100
  gradient_clip_val: 0.1

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./logs/task_centric_lpm_stage2
        verbose: true
        save_last: true
        save_top_k: -1
        every_n_train_steps: 2000

  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: ./logs
        name: task_centric_lpm_stage2
